backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "content/assets"

collections:
  - label: "About us"
    name: "about us"
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.md"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Path", name: "path", widget: "hidden", default: "about-us" }
          - { label: "Type", name: "type", widget: "hidden", default: "page" }
          - { label: "Body", name: "body", widget: "markdown" }